export default {
    GET_PROPERTIES: 'GET_PROPERTIES',
    REGISTER: 'REGISTER',
    SIGN_IN: 'SIGN_IN',
    INCORRECT_CREDENTIALS: 'INCORRECT_CREDENTIALS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR', 
    LOAD_NAV: 'LOAD_NAV',
}